### ISSUE TITLE
Scaffold the multiplatform project structure

### ISSUE THREAD

**Issue by HugoKempfer** [HugoKempfer/convey#1]
This repo will hold all client infrastructure components:
- common shared lib
- vue web app
- desktop electron app
- mobile ionic app
- node or deno CLI app

All components should be set up and build together prior to any other work.

## Todo

- [ ] common lib
- [ ] vue web app
- [ ] desktop electron app
- [ ] mobile ionic app
- [ ] CLI app
